austinjavascript/austinjavascript.com

_config.yml
_includes/people.html
about/index.md
css/style.scss
index.html

add about page

---

_posts/2016-11-10-meetup.md

@lawnsea @beaktor @jonloyens
pertains to #38

donut driven development

---

_posts/2017-01-09-meetup.md

@hxlnt lmk what you think, esp if i got the links for your projects correct
@beaktor all good?
@lawnsea

why hello, 2017

---

_posts/2017-03-13-meetup.md

@lawnsea @beaktor @tgrochowicz @linclark @lukewagner have a look and let me know if anything needs to change, otherwise we'll post this today!

um yea i know what webassembly is i window.Promise

---

_posts/2017-06-20-meetup.md

Hey @taravancil and @pfrazee, please have a look and lemme know what issues you find.

Meep! Meep meep

---

_config.yml

add this cool kid to the organizers

---

_posts/2017-08-15-meetup.md

@rmurphey @drewml @aaronj1335 have a look, please

August blog post

---

_posts/2016-08-09-meetup.md

this is how amazing this change looks do u love my cascading style sheet skills find me on linkedin
/cc @davatron5000

add link 2 amazing grandpa dave slides from 2017-08-15 PWA talk wow

---

austinjs-code-of-conduct/index.md

Added @rmurphey and removed @aaronj1335 until he's back from babbycation.

Replace Aaron with Rebecca on the CoC page

---

_posts/2017-09-19-meetup.md

Heyo, @rmurphey @aaronj1335 @howardr @benvinegar

Sep 2017 blog post: wait can we call it a ben vinaigreet and meet

---

_posts/2017-10-17-meetup.md

October 2017 meetup take 2

---

_posts/2017-11-13-meetup.md

@lawnsea @rmurphey @mando @beaktor @stedman what u think team
pertains to #62

we gonna find out what kubernetes means tho?

---

_posts/2018-01-16-meetup.md

@aaronj1335, @rmurphey, @bmeck, what do you think?

january-blog-post.mjs

---

_posts/2018-06-19-meetup.md

improve time to first sigh of satisfaction

---

_posts/2018-08-21-meetup.md

August meetup blog post

---

_posts/2018-10-16-meetup.md

October meetup blog post (#78)

---

_posts/2019-01-15-meetup.md

January meetup blog post

---

_posts/2019-02-19-meetup.md

February meetup blog post

---

_posts/2019-04-16-meetup.md

Please have a look, @creationix.

April meetup blog post (#86)

---

_posts/2019-10-14-meetup.md

October 2019 blog post

---

_posts/2019-11-18-meetup.md

November 2019 blog post

---

CONTRIBUTING-POSTS.md
README.md

Some of the wording needed tweakage. The link in README was borked.
Fix It

Update contribution instructions

---

CONTRIBUTING-POSTS.md
_posts/2010-02-16-meetup.md
_posts/2011-01-18-meetup.md
_posts/2011-02-15-meetup.md
_posts/2011-04-19-meetup.md
_posts/2011-06-21-meetup.md
_posts/2011-07-19-meetup.md
_posts/2012-01-17-meetup.md
_posts/2012-04-17-meetup.md
_posts/2012-07-17-meetup.md
_posts/2012-08-21-meetup.md
_posts/2013-06-18-meetup.md
_posts/2013-07-16-meetup.md
_posts/2013-10-15-meetup.md
_posts/2014-07-15-meetup.md
_posts/2016-04-19-meetup.md
_posts/2016-08-16-meetup.md
_posts/2016-11-15-meetup.md
_posts/2017-09-19-meetup.md
_posts/2017-10-17-meetup.md
_posts/2017-11-21-meetup.md
_posts/2018-01-16-meetup.md
_posts/2018-02-20-meetup.md
_posts/2018-06-19-meetup.md
_posts/2018-07-17-meetup.md
_posts/2018-08-21-meetup.md
_posts/2018-09-18-meetup.md
_posts/2018-10-16-meetup.md
_posts/2019-01-15-meetup.md

* Fix MarkdownLint issues.
* Add presentation slide and video links for future use (see slide and video icons at http://stedman.github.io/ajs-11ty/posts/ )

Add presentation links, fix MD issues

---

_includes/filters/markdown.js
_includes/shortcodes/avatar.js
_includes/social-links.liquid
about.liquid

* Added a try/catch to avatar shortcode.
* Repaired other anomalies that followed the change to LiquidJS.
* Tweaked words.

Fix avatar cache warming

---

_layouts/base.liquid

...and to remove console warning

Move differential scripts to head to improve performance
